# services:
#   - docker
language: python
python:
  - 3.7
os:
  - linux
dist: xenial
install:
  - pip install cwltool
branches:
  only:
   - release
cache: pip
script: find . -name "*.cwl" | xargs -n1 cwltool --validate
