# services:
#   - docker
language: python
python:
  - 3.7
os:
  - linux
dist: xenial
install:
  - pip install cwltool
branches:
  only:
   - release
cache:
  pip: true
  directories:
    - ${HOME}/.cache/salad
script: git diff --name-status origin/release..$(git branch | grep \* | cut -d ' ' -f2) | 
  
  #find . -name "*.cwl" | xargs -n1 cwltool --validate
